### ISSUE TITLE
Error with 1.8.5 on 1.12.2

### ISSUE THREAD

**Issue by MateoNikolic** [TlatoaniHJ/MundoSK#31]
### Bug Report

Skript Version: 2.2-dev36

MundoSK Version: 1.8.5

Minecraft Version: 1.12.2

### Steps to Reproduce the Issue

[13:57:10 ERROR]: [MundoSK] Unhandled exception number 32 occured in onPacketSending(PacketEvent) for MundoSK
java.lang.LinkageError: com/comphenix/protocol/wrappers/PlayerInfoData
        at com.comphenix.protocol.events.PacketContainer.getPlayerInfoDataLists(PacketContainer.java:687) ~[?:?]
        at mundosk_libraries.packetwrapper.WrapperPlayServerPlayerInfo.getData(WrapperPlayServerPlayerInfo.java:49) ~[?:?]
        at com.pie.tlatoani.Tablist.TablistManager.lambda$loadPacketEventListeners$2(TablistManager.java:214) ~[?:?]
        at com.pie.tlatoani.ProtocolLib.PacketManager$1.onPacketSending(PacketManager.java:152) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokeSendingListener(SortedPacketListenerList.java:195) ~[?:?]
        at com.comphenix.protocol.injector.SortedPacketListenerList.invokePacketSending(SortedPacketListenerList.java:149) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.handlePacket(PacketFilterManager.java:588) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.invokePacketSending(PacketFilterManager.java:564) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.packetQueued(ProtocolInjector.java:338) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector.onPacketSending(ProtocolInjector.java:298) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.processSending(ChannelInjector.java:378) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.access$800(ChannelInjector.java:64) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.handleScheduled(ChannelInjector.java:343) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3.onMessageScheduled(ChannelInjector.java:313) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelProxy$2.schedulingRunnable(ChannelProxy.java:127) ~[?:?]
        at com.comphenix.protocol.injector.netty.EventLoopProxy.execute(EventLoopProxy.java:95) ~[?:?]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:209) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.NetworkManager.sendPacket(NetworkManager.java:157) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.PlayerConnection.sendPacket(PlayerConnection.java:1203) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setPlayerListName(CraftPlayer.java:302) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at nl.marido.deluxecombat.objects.RankingSystem.applyDisplayname(RankingSystem.java:290) ~[?:?]
        at nl.marido.deluxecombat.objects.RankingSystem.updatePlayers(RankingSystem.java:244) ~[?:?]
        at nl.marido.deluxecombat.objects.RankingSystem.access$2(RankingSystem.java:241) ~[?:?]
        at nl.marido.deluxecombat.objects.RankingSystem$2.run(RankingSystem.java:539) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:852) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:786) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:678) ~[KyodoSpigot.jar:git-Paper-33d42c8e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Govindass** [comment]
ProtocolLib version?
