### ISSUE TITLE
[Paper1.12.2] MundoSk did break Script.

### ISSUE THREAD

**Issue by Sakuraga200323** [TlatoaniHJ/MundoSK#35]
### Bug Report
When I add MundoSk in plugins file.
All Skript were not worked.
Could you fix it...?

Skript Version (and other info):
```
[11:26:25 ERROR]: #!#! Version Information:
[11:26:25 ERROR]: #!#!   Skript: 2.6.1 (latest)
[11:26:25 ERROR]: #!#!     Flavor: skriptlang-github
[11:26:25 ERROR]: #!#!     Date: 22:18:42.554713200
[11:26:25 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:26:25 ERROR]: #!#!   Minecraft: 1.12.2
[11:26:25 ERROR]: #!#!   Java: 1.8.0_312 (OpenJDK 64-Bit Server VM 25.312-b07)
[11:26:25 ERROR]: #!#!   OS: Linux amd64 4.15.0-153-generic
```

MundoSK Version:
I tried [MundoSK 1.8.5] and [MundoSK 1.8.6-BETA.57]

### Console Errors (if applicable)
```
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! [Skript] Severe Error:
[11:25:01 ERROR]: #!#! Could not load EV-onJoin.sk
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Something went horribly wrong with Skript.
[11:25:01 ERROR]: #!#! This issue is NOT your fault! You probably can't fix it yourself, either.
[11:25:01 ERROR]: #!#! It looks like you are using some plugin(s) that alter how Skript works (addons).
[11:25:01 ERROR]: #!#! Here is full list of them:
[11:25:01 ERROR]: #!#! skRayFall v1.9.12 (http://sk.rayfall.net/) SkriptJSON v1.0.0 skript-reflect v2.2.3 (https://github.com/TPGamesNL/skript-reflect) SkRage v2.4.2 skDragon v0.16 SkBee v1.10.2 (https://github.com/ShaneBeee/SkBee) skUtilities v0.9.2 (https://tim740.github.io/) MundoSK v1.8.6-BETA.57 (https://forums.skunity.com/resources/mundosk.69/) SkQuery v4.1.5 Skent v3.1.0 DiscordSRV v1.24.0 (https://github.com/DiscordSRV/DiscordSRV) 
[11:25:01 ERROR]: #!#! We could not identify which of those are specially related, so this might also be Skript issue.
[11:25:01 ERROR]: #!#! You should try disabling those plugins one by one, trying to find which one causes it.
[11:25:01 ERROR]: #!#! If the error doesn't disappear even after disabling all listed plugins, it is probably Skript issue.
[11:25:01 ERROR]: #!#! In that case, you will be given instruction on how should you report it.
[11:25:01 ERROR]: #!#! On the other hand, if the error disappears when disabling some plugin, report it to author of that plugin.
[11:25:01 ERROR]: #!#! Only if the author tells you to do so, report it to Skript's issue tracker.
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Stack trace:
[11:25:01 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for attributeinstance
[11:25:01 ERROR]: #!#!     at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:263)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.fromString(TypePatternElement.java:92)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:132)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternCompiler.compile(PatternCompiler.java:48)
[11:25:01 ERROR]: #!#!     at java.util.HashMap.computeIfAbsent(HashMap.java:1128)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1301)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:523)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:800)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:126)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.OptionalPatternElement.match(OptionalPatternElement.java:46)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.ParseTagPatternElement.match(ParseTagPatternElement.java:79)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.TypePatternElement.match(TypePatternElement.java:121)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.PatternElement.matchNext(PatternElement.java:54)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.LiteralPatternElement.match(LiteralPatternElement.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.ChoicePatternElement.match(ChoicePatternElement.java:63)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.GroupPatternElement.match(GroupPatternElement.java:47)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.patterns.SkriptPattern.match(SkriptPattern.java:57)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1302)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:226)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.Condition.parse(Condition.java:77)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.sections.SecConditional.init(SecConditional.java:83)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.Section.init(Section.java:69)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:257)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:179)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.Section.lambda$parse$0(Section.java:157)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.Section$SectionContext.modify(Section.java:190)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.lang.Section.parse(Section.java:156)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:1127)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:752)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$loadScripts$4(ScriptLoader.java:525)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.lambda$makeFuture$2(ScriptLoader.java:417)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.makeFuture(ScriptLoader.java:433)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:524)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:468)
[11:25:01 ERROR]: #!#!     at ch.njol.skript.Skript$1.run(Skript.java:778)
[11:25:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
[11:25:01 ERROR]: #!#!     at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[11:25:01 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840)
[11:25:01 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[11:25:01 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[11:25:01 ERROR]: #!#!     at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[11:25:01 ERROR]: #!#!     at java.lang.Thread.run(Thread.java:748)
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Version Information:
[11:25:01 ERROR]: #!#!   Skript: 2.6.1 (latest)
[11:25:01 ERROR]: #!#!     Flavor: skriptlang-github
[11:25:01 ERROR]: #!#!     Date: 22:18:42.554713200
[11:25:01 ERROR]: #!#!   Bukkit: 1.12.2-R0.1-SNAPSHOT
[11:25:01 ERROR]: #!#!   Minecraft: 1.12.2
[11:25:01 ERROR]: #!#!   Java: 1.8.0_312 (OpenJDK 64-Bit Server VM 25.312-b07)
[11:25:01 ERROR]: #!#!   OS: Linux amd64 4.15.0-153-generic
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Server platform: Paper
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Current node: if {slant.players::*} isn't set: (EV-onJoin.sk, line 6)
[11:25:01 ERROR]: #!#! Current item: null
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Thread: Server thread
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! Language: english
[11:25:01 ERROR]: #!#! Link parse mode: DISABLED
[11:25:01 ERROR]: #!#! 
[11:25:01 ERROR]: #!#! End of Error.
[11:25:01 ERROR]: #!#! 
```

### Other Useful Info (ex. addons and plugins you are using)
https://media.discordapp.net/attachments/936103697409269820/950222703950970900/2022-03-07_11.45.03.png

**Comment by ImNotStable** [comment]
Skript 2.6 dropped support for 1.12 and lower versions

**Comment by nennneko5787** [comment]
No.
Support for 1.12 and earlier will be discontinued starting with Skript 2.7
